# Generated by Django 5.0.6 on 2024-06-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
